config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'
  
  resources :posts, except: [:destroy] do
    post :vote, on: :member #will recognise /posts/id/vote with POST and route to vote method in PostsController
    resources :comments, only: [:create] do
      post :vote, on: :member #will recognise /posts/id/comments/id/vote vote with POST and route to vote method in CommentsController
    end
  end
    
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update ]
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  include VoteableKnoxjeffrey

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  
  validates :body, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_user
  
  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.creator = current_user
    
    if @comment.save
      flash[:notice] = "You successfully submitted your comment."
      redirect_to post_path(@post)
    else
      render "posts/show"
    end
  end
  
  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])
    
    respond_to do |format|
      format.html do
    
        if @vote.valid?
          flash[:notice] = "Your vote was counted"
        else
          flash[:danger] = "You can only vote once"
        end
    
        redirect_to :back
      end
      format.js
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
  
end

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class='row'>
  <div class="col-xs-1 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post,comment, vote: true), method: 'post', remote: true do %>
        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
      <% end %>
    <br/>
    <% else %>
      <%= render 'shared/no_click_thumb', thumb: "up"%>
    <br/>
    <% end %>
    <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %></span>
    <br/>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post,comment, vote: false), method: 'post', remote: true do %>
        <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
      <% end %>
    <br/>
    <% else %>
      <%= render 'shared/no_click_thumb', thumb: "down"%>
    <br/>
    <% end %>
  </div>
  <div class="col-xs-8 col-xs-offset-1 well">
    "<%= comment.body %>"
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    <p>
  		<span class='quiet'>by </span><%= link_to comment.creator.username, user_path(comment.creator) %>
  		<small>at <%= display_friendly_date(comment.created_at) %></small>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %>");
<% else %>
  alert("You can only vote on that comment once.");
<% end %>