config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'
  
  resources :posts, except: [:destroy] do
    post :vote, on: :member #will recognise /posts/id/vote with POST and route to vote method in PostsController
    resources :comments, only: [:create] do
      post :vote, on: :member #will recognise /posts/id/comments/id/vote vote with POST and route to vote method in CommentsController
    end
  end
    
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update ]
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  include VoteableKnoxjeffrey
  include Sluggable
  
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  
  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true
  
  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post_params, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show] #shut down routes if a user isn't logged in
  before_action :must_be_creator, only: [:edit, :update]
  
  def index
    @posts = Post.all.sort_by {|x| x.total_votes}.reverse
    
    respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.xml { render xml: @posts }
    end
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.creator = current_user
    
    if @post.save
      flash[:notice] = "You successfully created your post!"
      redirect_to posts_path
    else
      render :new
    end
  end
  
  def show
    @comment = Comment.new
  end
  
  def edit; end
  
  def update
    if @post.update(post_params)
      flash[:notice] = "You successfully edited your post!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end
  
  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
    
    #Any non ajaxified requests will follow the format.html block and the js requests will follow format.js.  
    #By not having a block for format.js it will try and do the default action of rendering a template, 
    #in this case a js template, called vote.js.erb.
    respond_to do |format|
      format.html do
        @vote.valid? ? flash[:notice] = "Your vote was counted" : flash[:danger] = "You can only vote once"

        redirect_to :back
      end
      format.js
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end
  
  def set_post_params
    @post = Post.find_by(slug: params[:id])
  end
  
  def must_be_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end
  
end

app/views/posts/_form.html.erb
<div class="col-sm-8 well">
	<%= form_for @post do |f| %>

		<%= render 'shared/errors', controller_object: @post %>
	 
  		<div class="form-group">
  			<%= f.label :title %>
  			<%= f.text_field :title, class: "form-control" %>
  		</div>

  		<div class="form-group">
  			<%= f.label :url %>
  			<%= f.text_field :url, class: "form-control" %>
  		</div>

  		<div class="from-group">
  			<%= f.label :description %>
  			<%= f.text_area :description, rows: 5, class: "form-control"  %>
      </div>
      <br/>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |box| %>
        <% box.label(class: "checkbox-inline") { box.check_box(class: 'checkbox') + box.text } %>
      <% end %>
      <br/>
      <br/>
	    <%= f.submit @post.new_record? ? "Submit Post" : "Update Post", class: "btn btn-danger" %>

	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="col-xs-1 well text-center">
  <% if logged_in? %>
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
    <% end %>
  <br/>
  <% else %>
    <%= render 'shared/no_click_thumb', thumb: "up"%>
  <br/>
  <% end %>
  <span id="post_<%= post.slug %>_votes"><%= post.total_votes %></span>
  <br/>
  <% if logged_in? %>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
      <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
    <% end %>
  <% else %>
    <%= render 'shared/no_click_thumb', thumb: "down"%>
  <% end %>
</div>
<div class="col-xs-10 col-xs-offset-1 well">
	<%= render post.categories %>
	<h4><%= link_to post.title, url_with_protocol(post.url) %></h4>
	<p><%= post.description %></p>
	<p>
		<span class='quiet'>posted by </span><%= link_to post.creator.username, user_path(post.creator) %>
		<small>on <%= display_friendly_date(post.created_at) %></small>
	</p>
	<span>
		<%= link_to("#{post.comments.size} comments", post_path(post))%>
	</span>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit Post"%>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts"%>

<% if logged_in? %>
  <div class="col-xs-12 well text-center">
    <%= link_to new_post_path, "tabindex" => "0", "data-toggle" => "popover", "data-trigger" => "hover", "data-content" => "Click to create a new post!" do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    <% end %>
  </div>
<% end %>

<% @posts.each do |post| %>
	<%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create New Post"%>

<%= render 'form' %>

app/views/posts/show.html.erb
<%if logged_in? && current_user == @post.creator || logged_in? && current_user.admin? %>
  <p class='pull-right'>
  	<%= link_to 'edit this post', edit_post_path(@post), class: 'btn btn-danger btn-small' %>
  </p>
<% end %>

<p>
	<%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>


<div class='row'>
  <div class="col-xs-12 well">
    <p><%= @post.description %></p>
  </div>
</div>

<% if logged_in?%>
  <div class='row'>
  	<div class='col-sm-8 well'>
      <%= form_for [@post, @comment] do |f| %>
        <%= render 'shared/errors', controller_object: @comment %>
 
      	<div class="form-group">
      		<%= f.label :body, "Leave A Comment" %>
      		<%= f.text_area :body, rows: 5, class: "form-control" %>
      	</div>
        </br>
        <%= f.submit "Create Comment", class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
<% end%>

<% if !@post.reload.comments.empty? %>
  <h5>Comments:</h5>
  <br/>
<% end %>

<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %>");
<% else %>
  alert("You can only vote on that post once.");
<% end %>