config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'
  
  resources :posts, except: [:destroy] do
    post :vote, on: :member #will recognise /posts/id/vote with POST and route to vote method in PostsController
    resources :comments, only: [:create] do
      post :vote, on: :member #will recognise /posts/id/comments/id/vote vote with POST and route to vote method in CommentsController
    end
  end
    
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update ]
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  
  has_many :post_categories
  has_many :posts, through: :post_categories
  
  validates :name, presence: true, uniqueness: true, length: {minimum: 2} 
  
  sluggable_column :name
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :require_user, except: [:show] #shut down routes if a user isn't logged in
  before_action :require_admin, except: [:show]
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "You successfully created your category"
      redirect_to root_path
    else
      render :new
    end
    
  end
  
  def show
    @category = Category.find_by(slug: params[:id])
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "Create New Category"%>

<div class = 'col-sm-8 well'>
	<%= form_for @category do |f| %>
	
		<%= render 'shared/errors', controller_object: @category %>
	
		<div class="form-group">
			<%= f.label :name, "Category Name" %>
			<%= f.text_field :name, class: "form-control" %>
		</div>
		<br/>
		<%= f.submit "Create Category", class: "btn btn-danger" %>
	<% end %>
	
</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>

<%= render 'shared/content_title', title: header  %>

<% @category.posts.each do |post| %>
	<%= render 'posts/post', post: post %>
<% end %>