config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'
  
  resources :posts, except: [:destroy] do
    post :vote, on: :member #will recognise /posts/id/vote with POST and route to vote method in PostsController
    resources :comments, only: [:create] do
      post :vote, on: :member #will recognise /posts/id/comments/id/vote vote with POST and route to vote method in CommentsController
    end
  end
    
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update ]
  
end

app/views/layouts/_messages.html.erb
<div class = 'col-sm-12'>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %>" role="alert">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria controls="navbar">
    <span class="sr-only">Toggle Navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to "PostIt!", root_path, :class => 'navbar-brand' %>
</div>  

<div id="navbar" class="collapse navbar-collapse">
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
    	<%= link_to "#", class: "dropdown-toggle", "data-toggle" => 'dropdown', "role" => "button" do  %>
        Categories <span class='caret'>
      <% end %>
      <ul class="dropdown-menu" role="menu">
        <% Category.all.each do |category| %>
          <li><%= link_to category.name, category_path(category) %></li>
        <% end %>
        <% if logged_in? and current_user.admin? %>
          <li class='divider'></li>
          <li>
            <%= link_to(new_category_path) do %>
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
              New Category
            <% end %>
          </li>
        <% end %>
      </ul>
    </li>
    <% if logged_in? %>
      <li class="dropdown">
      	<%= link_to '', class: "dropdown-toggle", "data-toggle" => 'dropdown', "role" => "button" do  %>
          <%= current_user.username %> <span class='caret'>
        <% end %>
        <ul class="dropdown-menu" role="menu">
          <li>
            <%= link_to edit_user_path(current_user) do %>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> edit profile
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user) do %>
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> view profile
            <% end %>
          </li>
          <li>
            <%= link_to logout_path do %>
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span> log out
            <% end %>
          </li>
        </ul>
      </li>
    <% else %>
      <li>
        <%= link_to 'Log In', login_path %>
      </li>
      <li class='active'>
        <%= link_to 'Register', register_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="Reddit Clone">
    <meta name="author" content="Jeff Knox">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>